import '@/styles/globals.css'
import { getAccessToken } from '@auth0/nextjs-auth0'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import { Inter } from 'next/font/google'

import { ApolloWrapper } from '@/lib/apollo/wrapper'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}): Promise<React.ReactElement> {
  const { accessToken } = await getAccessToken()

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ApolloWrapper accessToken={accessToken}>{children}</ApolloWrapper>
        </UserProvider>
      </body>
    </html>
  )
}
