name: 'Chromatic'

on:
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Clean install using pnpm
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build --filter=ui

      - name: Unit Test
        run: pnpm run test --filter=ui...

      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/ui
